---
title: "Meeting notes"
author:
- Martin Schobben
- Ilja Kocken
- Peter Bijl
date: "17 March, 2021"
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r  root, include = FALSE}
here::i_am("README.Rmd")
```


```{r pkgs, include=FALSE}
invisible(lapply(c("here", "tidyverse"), library, character.only = TRUE))
```

```{r ghost_paths}
project_path <- here("data-example/my-amazing-project")
data_path <- here("data-example/data/")
```

The goal of this meeting is to find optimal solutions to visualise your data. This PPGU workshop is especially addressing the needs for good figures for the up-and-coming NAC meeting.

# Reproducible workflow

## Structure

## Project setup

## Data management

Accessing your data in the organised structure. The use of explicit file paths

```{r paths, eval=FALSE}
project_path <- "...complete_path.../my-amazing-project"
data_path <- "...complete_path.../data"
```

The use of symlinks

```{r symlink}
file.symlink(data_path, file.path(project_path, "data"))
```

# Reading data

```{r palyno}
# install.packages("readr")
# library(readr) is already loaded with tidyverse
bonenburg_palyno <- read_csv(
  file.path("data-example/data/pollen_spores/Bonenburg_palyno.csv"), 
  col_types = "d--ddddddd-"
  )
```
